### ISSUE TITLE
Bug , Dont work the download

### ISSUE THREAD

**Issue by Stromgald** [jimgraham/NetSparkle#1]
There is an error on line 507 in netSpakle.cs  

```
this.ProgressWindow.ShowDialog();
```

This line should be put under  

```
Uri url = new Uri(item.DownloadLink);
            _webDownloadClient.DownloadFileAsync(url, _downloadTempFileName);
```

Or the download and events will never start.

By the way , thanks for this fork. You saved me a lot of time , cause i was changing the source to use with only 1 check instead of loop.

**Comment by jimgraham** [comment]
Thanks, I will investigate.
